### PR TITLE
Adds Occitan locale

### PR DESCRIPTION
**Pull request by ensag-dev**
I hope this is okay and I made all the required changes

### CODE REVIEW

**Comment by shaack** [comment]
OK, nice, thank you.

**Comment by shaack** [comment]
I removed Occitan again because it's meant to allow you to add your own language via the props.

**Comment by ensag-dev** [comment]
Hello @shaack ,
how will people be aware of my contribution then? And the availability of the language?

**Comment by shaack** [comment]
We could add it as an example on how to add locales/translations via props.

[EDIT]
I did it: https://shaack.com/projekte/cookie-consent-js/examples/cookie-consent-add-translations.html

Is that okay with you? We can't include all the languages of the world in the source code, so adding additional languages via props is the preferred way.

**Comment by shaack** [comment]
Hi, with 2.0.0 I changed the architecture. It now works with language files: https://github.com/shaack/cookie-consent-js/tree/master/cookie-consent-content

**Comment by Mejans** [comment]
this looks like a good solution, thank you

**Pull request merged**
