### PR TITLE
Turkish language added

### PR DESCRIPTION
**Pull request by Ardakilic**
Heya,

I've translated the strings for Turkish language support.

Thanks!

### CODE REVIEW

**Comment by shaack** [comment]
Cool, thanks! One thing, you have to keep `--privacy-policy--` instead of `--gizlilik sözleşmesi--` because it will be automatically replaced with the link to the privacy policy.

**Comment by Ardakilic** [comment]
Hey @shaack , thanks for the heads-up! It should be fine now.

**Comment by shaack** [comment]
With 2.0.0 I changed the architecture. It now supports language files https://github.com/shaack/cookie-consent-js/tree/master/cookie-consent-content

**Comment by Ardakilic** [comment]
Hey @shaack , awesome, thanks for the merge and the updated architecture feature! Looks great!

**Pull request merged**
